### ISSUE TITLE
Here is the issue I met

### ISSUE THREAD

**Issue by ThaiLe011094** [gmanny/EdgePasswordImport#1]
C:\Users\Thai>"D:\Downloads\EdgePasswordImport\EdgePasswordImport.exe"
Failed to import account for android://[redacted] with login [redacted] and password length 0 with error:
System.ArgumentException: The parameter is incorrect.

Cannot create credential
   at Windows.Security.Credentials.PasswordCredential..ctor(String resource, String userName, String password)
   at EdgePasswordImport.Program.Main(String[] args) in C:\Users\gmany\Documents\EdgePasswordImport\EdgePasswordImport\Program.cs:line 75
Failed to import account for https://t[redacted] with login  and password length [redacted] with error:
System.ArgumentException: The parameter is incorrect.

Cannot create credential
   at Windows.Security.Credentials.PasswordCredential..ctor(String resource, String userName, String password)
   at EdgePasswordImport.Program.Main(String[] args) in C:\Users\gmany\Documents\EdgePasswordImport\EdgePasswordImport\Program.cs:line 75
Imported 221 credentials.
Failed to import 2 credentials.

_______________________________________________________________________________________________________________
I checked the Edge and I found no passwords were imported too. What should I do? Thank you so much!

**Comment by gmanny** [comment]
I see that it has successfully imported most of the credentials: `Imported 221 credentials.` and only two of them were invalid (first has no password and is for something strange, second one has no login).

Can you check if the credentials are visible in Edge when you open Settings, go to advanced settings and press the "manage passwords" button there?

**Comment by ThaiLe011094** [comment]
Hello gmanny. I'm so sorry for a late response. I saw that line too but the fact was that it imported nothing. By the way, I'm using windows 10 Pro build 17735r5 180807-1451, the Edge changed a bit in this Windows version but I didn't know whether that would affect the method of your program. Thanks again!

**Comment by gmanny** [comment]
Oh, I see, so that's an Insider build? I'll set a new box up with the insider stuff and check it out. Right now I'm on a slow internet and can't do this immediately, but will keep you posted!
________________________________

**Comment by ThaiLe011094** [comment]
You are so great. Thank you so much!

**Comment by gmanny** [comment]
I've checked the tool in insider preview build 17741.rs5_release.180814-1430 (current Fast ring build) and it worked as expected. So let's debug further.

Could you create a CSV file with this text:
```csv
name,url,username,password
test_entry,https://www.reddit.com/login,login,P@ssw0rd123
```

And import it through the tool. Then go to https://www.reddit.com/ in Edge, (log out if logged in) and press a login button. In the login dialog, click the "username" field and see if the popup with the login "login" appears and Edge is able to fill the fake password in? You can also check if the password is in the Settings -> Passwords&autofill -> Manage passwords and then remove it as it's garbage data.

If this primitive file works, then my tool trips up on some records in your exported file and I'll look through the code further and add some more logging to check what's happening as I admit I ignore whether the credential creation succeeds or not. If this small file also fails, we'll check which GUID marks credentials usable by Edge on your machine.

**Comment by ThaiLe011094** [comment]
Hi gmanny, thank you for your support, it worked finally. Before trying your new method, I decided try it myself with just clear all the browser data, login into safe mode and re-run your tool again, magically it worked perfectly. You are awesome, thank you XD

**Comment by gmanny** [comment]
Glad you had this issue fixed! Just a heads up, I'm going to delete this issue in 24 hours to protect the details you posted in the log in the first post.
