### ISSUE TITLE
Not sure if it worked....

### ISSUE THREAD

**Issue by eklaburn1** [gmanny/EdgePasswordImport#2]
I've imported my passwords, thanks, but unfortunately edge refuses to suggest them in the browser.... :( Next to the passwords in settings I see a key icon in place of the site icons, not sure if thats related and means they are locked or what? Thanks!

**Comment by gmanny** [comment]
I can investigate, for this I'll need your version of Windows (first line that `cmd.exe` outputs when started, like `Version 10.0.17763` for example) to know which version of Edge you've got.

The header of your CSV file, which is normally a first line and looks like this: `name,url,username,password`

And then a couple of lines from the CSV file (you can open the `.csv` file with a Notepad in Windows), ideally for a popular sites. **Please replace logins and passwords with the words `login` and `password`.** Looking something like this:

```
www.reddit.com,https://www.reddit.com/login,test_login,test_password
```

Do not reformat the lines, just replace the personal information in them as I'll try to check that the lines are correct.

**Comment by eklaburn1** [comment]
Hi! Thanks a lot :) Version 10.0.17134.407 of windows &
version 42.17134.1.0 of edge.
name,url,username,password
abs-cbn.com,http://abs-cbn.com/,username,password
<http://abs-cbn.com/,username,password?fbclid=IwAR1Qkdbx3F4Iwz7Ysmt4msv-wUZRJFuWPMlDrz_GOzTVXo8_3OOMnvScaBI>
agoda.com,https://agoda.com/,username@gmail.com,password
<https://agoda.com/,username@gmail.com,password?fbclid=IwAR1xoaQ5K8ScEpvf5kjlwYDlA_J-2pq8XdLUiaaw4jGZ8yiUvQ-b8vvAAB0>
ahrefs.com,https://ahrefs.com/,username@gmail.com,password
<https://ahrefs.com/,username@gmail.com,password?fbclid=IwAR1ckjzT_f8RMnPbitlNC2nkWXyl0gq7mTx08w0-v19Z6mlUiMSDuwk26DM>

**Comment by gmanny** [comment]
Looks like Edge and Chrome match URLs for password auto-fill differently, so first two web sites do not get recognized. I was able to make Edge recognize both passwords by checking the URLs of login pages and changing them in a CSV like so (the second one missed a `www.` at the start and it was enough to confuse Edge, unfortunately):

```
name,url,username,password
abs-cbn.com,https://kapamilya-accounts.abs-cbn.com/,username,password
agoda.com,https://www.agoda.com/,username@gmail.com,password
```

The third one (ahrefs.com) actually worked as it should, could you check if it works in your browser as well?

P.S. The key icons are not a problem, those are just placeholder icons for sites that don't have their favicon cached.

**Comment by eklaburn1** [comment]
Thanks. I'm just going to switch back to Chrome. It's crazy MS makes this
so difficult considering how hard they are pushing Edge.

**Comment by gmanny** [comment]
Sure, I understand! This might change when they support importing passwords themselves and thus encounter this issue as unfortunately right now Edge requires additional data in the URL that Chrome does not store.

P.S. Don't forget to turn the password export off in chrome://flags
